### PR TITLE
Fix bug with thumbnail being the same for every product.

### LINKED ISSUE #1: Search returns the same thumbnail for all products
Hi, first of all, thanks for sharing this project, it's a big time-saver.
I've encountered an issue where when using the search endpoint, every product has the same thumbnail, using Lunar directly it returns the correct images.

Here is an example, note that I removed parts of the JSON just to make it shorter
`{
    "data": [
        {
            "id": 1,
            "slug": "test-1",
            "thumbnail": {
                "url": "http:\/\/localhost:8000\/storage\/10\/lshZr2b0mBROgf6jGgVNN3bQS722X6-metaQ2FudmFzNC5qcGc=-.jpg",
                "label": "Thumbnail",
                "mime_type": "image\/jpeg"
            }
        },
        {
            "id": 4,
            "slug": "test",
            "thumbnail": {
                "url": "http:\/\/localhost:8000\/storage\/10\/lshZr2b0mBROgf6jGgVNN3bQS722X6-metaQ2FudmFzNC5qcGc=-.jpg",
                "label": "Thumbnail",
                "mime_type": "image\/jpeg"
            }
        },
        {
            "id": 5,
            "slug": "test-1",
            "thumbnail": {
                "url": "http:\/\/localhost:8000\/storage\/10\/lshZr2b0mBROgf6jGgVNN3bQS722X6-metaQ2FudmFzNC5qcGc=-.jpg",
                "label": "Thumbnail",
                "mime_type": "image\/jpeg"
            }
        },
        {
            "id": 2,
            "slug": "wqeqwewwqe",
            "thumbnail": {
                "url": "http:\/\/localhost:8000\/storage\/10\/lshZr2b0mBROgf6jGgVNN3bQS722X6-metaQ2FudmFzNC5qcGc=-.jpg",
                "label": "Thumbnail",
                "mime_type": "image\/jpeg"
            }
        }
    ]
}`

Thank you

### PR DESCRIPTION
**Pull request by webdo**
Fixes #1 

Using $this->thumbnail->first would return the same thumbnail for every products.

### CODE REVIEW

**Comment by SrPatinhas** [comment]
@webdo thanks for the commit, but could you change the return to be `null` instead of `""`? It would be easier, being the return value an object, this way would be a null value

File: app/Http/Resources/LunarAPI/Brand/BrandResource.php [hunk 1]
```diff
@@ -18,7 +18,8 @@ public function toArray(Request $request): array
         return [
             "id"    => $this->id,
             "name"  => $this->name,
-            "logo"  => new MediaThumbnailResource($this->thumbnail->first()),
+            "logo"  => $this->thumbnail ? new MediaThumbnailResource($this->thumbnail->first()) : ""
```
Comment (SrPatinhas) [inline app/Http/Resources/LunarAPI/Brand/BrandResource.php]: the `->first()` also needs to be removed in this line

Comment (webdo) [reply app/Http/Resources/LunarAPI/Brand/BrandResource.php]: You are right, I totally forgot to remove it on that line too.
